name: 'Bad Action'
description: 'Example of the importance of hashing actions'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: run.sh
      shell: bash
